### ISSUE TITLE
No icons in production

### ISSUE THREAD

**Issue by davidw** [mjonuschat/bootstrap-sass-rails#13]
Not sure if it's user error, but this gem works perfectly in development mode, and in production does not display the icons.

The paths are different:

development:

```
background-image: url(/assets/twitter/bootstrap/glyphicons-halflings.png);
```

production:

```
  background-image: image-url("twitter/bootstrap/glyphicons-halflings.png");
```

Not sure what is causing that, but clearly, the latter does not work.

**Comment by davidw** [comment]
This is version 2.0.2.0, Rails 3.2.2.

**Comment by mjonuschat** [comment]
That's pretty strange. The gem itself doesn't differentiate between development and production mode. It's more or less a bundled collection of Sass and Javascript files. Due to the "image-url" you are getting in production mode it seems to me that your assets don't get precompiled correctly.

Would you be able to share a small sample app that exhibits the problem?

**Comment by davidw** [comment]
After more investigation, we'll chalk this one up to the mess Rails makes with its assets pipeline.  Thanks for the quick answer.
