### ISSUE TITLE
Input's blue glow is hard coded

### ISSUE THREAD

**Issue by scomma** [mjonuschat/bootstrap-sass-rails#29]
It's an issue when the site's color scheme doesn't consist of blue much. [The offending line.](https://github.com/yabawock/bootstrap-sass-rails/blob/develop/vendor/assets/stylesheets/twitter/bootstrap/_forms.scss#L128)

Expected behavior: the constant `rgba(82,168,236,.6)` lives in `_variables.scss`

**Comment by mjonuschat** [comment]
Hi,
this behavior is consisten with the original LESS version of bootstrap. There have been multiple issues in the bootstrap project, a prominent one being [#2742](https://github.com/twitter/bootstrap/issues/2742). 

Since I'm sticking to the original as far as possible while porting to SASS to ease porting of future versions and this is pretty trivial to override with a simple statement in CSS I'll not be fixing it out of line with the original bootstrap. It would be best if you adressed this issue directly at the source.

Thanks!

**Comment by scomma** [comment]
That's perfectly understandable. Thanks!
