### ISSUE TITLE
Image path not correct

### ISSUE THREAD

**Issue by alainus** [mjonuschat/bootstrap-sass-rails#55]
In vendor/variables, you have:
`$iconSpritePath:        "twitter/bootstrap/glyphicons-halflings.png" !default;`

This should be:
`$iconSpritePath:          image-path("glyphicons-halflings.png") !default;`

This makes the icons not be on the default /assets/ path, and bootswatch can't find them.

**Comment by mjonuschat** [comment]
Hi,

having all assets namespaced to 'twitter/bootstrap' has been one of the design decisions I made for this gem. It's even mentioned in the first paragraph of the README. Since this project is adhering to Semantic Versioning moving the assets now would be a breaking change for everybody relying on the assets being at `twitter/bootstrap/...`. 

Additionally modifying the variables as you suggested wouldn't fix the problem but break the gem. The image assets are located at `vendor/assets/images/twitter/bootstrap/` on the filesystem. The image-path helper wouldn't magically move them to /assets/glyphicons-halflings.png, they would still need to be addressed in their subdirectories with something along the lines of `image-path("twitter/bootstrap/glyphicons-halflings.png")`. The output of that would be `twitter/bootstrap/glyphicons-halflings.png` again.

If you want to combine bootstrap-sass-rails and bootswatch-rails the easiest thing to do is declare the iconSpritePath variable up front without relying on the conflicting defaults of bootstrap-sass-rails or bootswatch-rails. Your application.css would look something like

``` scss
// First set or import your overrides
$iconSpritePath: image-path("twitter/bootstrap/glyphicons-halflings.png");

// Then load the bootswatch overrides
@import "bootswatch/journal/variables";

// Then bootstrap itself
@import "twitter/bootstrap";
```

Btw - I don't see why bootstrap-rails is overriding the iconSpritePath variable if it isn't setting a new non-standard value. I would consider this more of a bug in bootswatch-rails. Their variables should only declare values differing from the stock bootstrap distribution.
